name: validate-PR

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3

      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'

      ## for local act testing
      # - run: npm install -g yarn

      - run: yarn install

      - name: Validate PR
        run: yarn validate-PR >> $GITHUB_STEP_SUMMARY
